#______ SINTAXIS PARA DEFINIR UNA FUNCION 

""" def NOMBRE(PARAMETROS):
    SENTENCIAS
    return [EXPRESION] """

# NOMBRE: ES EL NOMBRE DE LA FUNCION
# PARAMETROS: en las funciones cuando recibe argumento se lo denomina parametros
# SENTENCIAS: ES EL BLOQUE DE CODIGO
# RETURN: ES UNA SENTENCIA DE PYTHON QUE LE INDICA A LA FUNCION QUE DEVOLVER CIANDO LA LLAMEMOS
# EXPRESION: ES LO QUE DEVUELVE LA SENTENCIA RETURN

def saludar():
    print("Hola, los estoy saludando")
#PARA LLAMARLA ESCRIBIMOS EL NOMBRE DE LA FUNCION
saludar()

